name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]
        xcode: ['15.2.0', '15.1.0']
        arch: [x86_64, arm64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Bundler
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: Cache Pods
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    
    - name: Install Dependencies
      run: |
        bundle install --path=vendor/bundle
        bundle exec pod install
        
    - name: Build
      run: |
        xcodebuild clean build \
          -workspace Clipy.xcworkspace \
          -scheme Clipy \
          -configuration Debug \
          -arch ${{ matrix.arch }} \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Run Tests
      run: |
        xcodebuild test \
          -workspace Clipy.xcworkspace \
          -scheme Clipy \
          -configuration Debug \
          -arch ${{ matrix.arch }} \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    