name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        xcode: ['15.2.0']
        arch: [x86_64, arm64]
    
    env:
      MD_APPLE_SDK_ROOT: /Applications/Xcode_${{ matrix.xcode }}.app
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    
    - name: Cache Bundler
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: Cache Pods
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    
    - name: Install Dependencies
      run: |
        gem install bundler
        gem install cocoapods
        bundle update --bundler
        bundle config build.nokogiri --use-system-libraries
        pod repo update
        bundle install --path=vendor/bundle
        pod install
    
    - name: Build
      run: |
        xcodebuild clean build \
          -workspace Clipy.xcworkspace \
          -scheme Clipy \
          -configuration Debug \
          -arch ${{ matrix.arch }} \
          -destination "platform=macOS,arch=${{ matrix.arch }}" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Run Tests
      run: |
        xcodebuild test \
          -workspace Clipy.xcworkspace \
          -scheme Clipy \
          -configuration Debug \
          -arch ${{ matrix.arch }} \
          -destination "platform=macOS,arch=${{ matrix.arch }}" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    